version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase"
      - "SPRING_DATASOURCE_USERNAME=myuser"
      - "SPRING_DATASOURCE_PASSWORD=secret"
      - "SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver"
      - "SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect"

    ports:
      - "8080:8080"
    depends_on:
      - postgres
