apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddrop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddrop-api
  template:
    metadata:
      labels:
        app: reddrop-api
    spec:
      containers:
        - name: reddrop-api
          image: docker.io/ramialkaro/reddrop-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: reddrop-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
